# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rater',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
