# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_recommender', '0002_auto_20160505_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rater',
            old_name='user_id',
            new_name='rater_id',
        ),
        migrations.AddField(
            model_name='rater',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
