# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_recommender', '0005_auto_20160509_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rater',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1),
        ),
    ]
